export const workplace = ['All', 'Mostovaya', 'Bogutskogo', 'DNT', 'Gaspadarchaya', 'Bogdanovicha'];
export const departments = ['HR-HRM', 'GD-1', 'GD-2', 'GD-3', 'GD-4', 'GD-5', 'GD-6', 'GD-7'];

export const users = [
  {
    id: 1,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov1',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 2,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov2',
    position: 'UX/UI Disigner',
    department: 'GD-6',
    workplace: ['Mostovaya'],
  },
  {
    id: 3,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov3',
    position: 'UX/UI Disigner',
    department: 'GD-1',
    workplace: ['Mostovaya', 'Gaspadarchaya'],
  },
  {
    id: 4,
    logo: 'logo.png',
    name: 'Ivan Aleksandrov4',
    position: 'UX/UI Disigner',
    department: 'GD-2',
    workplace: [],
  },
  {
    id: 5,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov5',
    position: 'UX/UI Disigner',
    department: 'GD-3',
    workplace: ['Mostovaya', 'Bogutskogo', 'Gaspadarchaya'],
  },
  {
    id: 6,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov6',
    position: 'UX/UI Disigner',
    department: 'GD-4',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 7,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov7',
    position: 'UX/UI Disigner',
    department: 'GD-5',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 8,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov8',
    position: 'UX/UI Disigner',
    department: 'GD-6',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 9,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov9',
    position: 'UX/UI Disigner',
    department: 'GD-7',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 10,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov10',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 11,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov11',
    position: 'UX/UI Disigner',
    department: 'GD-1',
    workplace: [],
  },
  {
    id: 12,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov12',
    position: 'UX/UI Disigner',
    department: 'GD-2',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 13,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'GD-3',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 14,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'GD-4',
    workplace: ['Mostovaya', 'Gaspadarchaya'],
  },
  {
    id: 15,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'GD-5',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 16,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'GD-6',
    workplace: [],
  },
  {
    id: 17,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'GD-7',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 18,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 19,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogutskogo', 'Gaspadarchaya'],
  },
  {
    id: 20,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 21,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogutskogo', 'Gaspadarchaya'],
  },
  {
    id: 22,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 23,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogutskogo', 'Gaspadarchaya'],
  },
  {
    id: 24,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 25,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'DNT', 'Gaspadarchaya'],
  },
  {
    id: 26,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 27,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 28,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['DNT', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 29,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 30,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 31,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'DNT', 'Gaspadarchaya'],
  },
  {
    id: 32,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 33,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 34,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'DNT'],
  },
  {
    id: 35,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 36,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 37,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Bogutskogo', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 38,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 39,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 40,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 41,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
  {
    id: 42,
    logo: 'logo.png',
    name: 'Oleg Aleksandrov',
    position: 'UX/UI Disigner',
    department: 'HR-HRM',
    workplace: ['Mostovaya', 'Bogdanovicha', 'Gaspadarchaya'],
  },
];
